# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  build_image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Build image
        uses: mamezou-tech/buildpacks-action@master
        with:
          image: 'springboot-github-actions'
          tag: ${{ github.sha }}
          path: '.'
          builder: 'heroku/buildpacks:18'
